version: '3.7'
services:
  mongo-db:
    image: mongo

    container_name: mongo-db
    volumes:
      - ./db/:/data/db



  golang-api:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mongo-db
    links:
      - mongo-db 