// Code generated by counterfeiter. DO NOT EDIT.
package routesfakes

import (
	"example-project/routes"
	"sync"

	"github.com/gin-gonic/gin"
)

type FakeHandlerInterface struct {
	CreateEmployeeHandlerStub        func(*gin.Context)
	createEmployeeHandlerMutex       sync.RWMutex
	createEmployeeHandlerArgsForCall []struct {
		arg1 *gin.Context
	}
	DeleteByIdHandlerStub        func(*gin.Context)
	deleteByIdHandlerMutex       sync.RWMutex
	deleteByIdHandlerArgsForCall []struct {
		arg1 *gin.Context
	}
	GetEmployeeHandlerStub        func(*gin.Context)
	getEmployeeHandlerMutex       sync.RWMutex
	getEmployeeHandlerArgsForCall []struct {
		arg1 *gin.Context
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHandlerInterface) CreateEmployeeHandler(arg1 *gin.Context) {
	fake.createEmployeeHandlerMutex.Lock()
	fake.createEmployeeHandlerArgsForCall = append(fake.createEmployeeHandlerArgsForCall, struct {
		arg1 *gin.Context
	}{arg1})
	stub := fake.CreateEmployeeHandlerStub
	fake.recordInvocation("CreateEmployeeHandler", []interface{}{arg1})
	fake.createEmployeeHandlerMutex.Unlock()
	if stub != nil {
		fake.CreateEmployeeHandlerStub(arg1)
	}
}

func (fake *FakeHandlerInterface) CreateEmployeeHandlerCallCount() int {
	fake.createEmployeeHandlerMutex.RLock()
	defer fake.createEmployeeHandlerMutex.RUnlock()
	return len(fake.createEmployeeHandlerArgsForCall)
}

func (fake *FakeHandlerInterface) CreateEmployeeHandlerCalls(stub func(*gin.Context)) {
	fake.createEmployeeHandlerMutex.Lock()
	defer fake.createEmployeeHandlerMutex.Unlock()
	fake.CreateEmployeeHandlerStub = stub
}

func (fake *FakeHandlerInterface) CreateEmployeeHandlerArgsForCall(i int) *gin.Context {
	fake.createEmployeeHandlerMutex.RLock()
	defer fake.createEmployeeHandlerMutex.RUnlock()
	argsForCall := fake.createEmployeeHandlerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHandlerInterface) DeleteByIdHandler(arg1 *gin.Context) {
	fake.deleteByIdHandlerMutex.Lock()
	fake.deleteByIdHandlerArgsForCall = append(fake.deleteByIdHandlerArgsForCall, struct {
		arg1 *gin.Context
	}{arg1})
	stub := fake.DeleteByIdHandlerStub
	fake.recordInvocation("DeleteByIdHandler", []interface{}{arg1})
	fake.deleteByIdHandlerMutex.Unlock()
	if stub != nil {
		fake.DeleteByIdHandlerStub(arg1)
	}
}

func (fake *FakeHandlerInterface) DeleteByIdHandlerCallCount() int {
	fake.deleteByIdHandlerMutex.RLock()
	defer fake.deleteByIdHandlerMutex.RUnlock()
	return len(fake.deleteByIdHandlerArgsForCall)
}

func (fake *FakeHandlerInterface) DeleteByIdHandlerCalls(stub func(*gin.Context)) {
	fake.deleteByIdHandlerMutex.Lock()
	defer fake.deleteByIdHandlerMutex.Unlock()
	fake.DeleteByIdHandlerStub = stub
}

func (fake *FakeHandlerInterface) DeleteByIdHandlerArgsForCall(i int) *gin.Context {
	fake.deleteByIdHandlerMutex.RLock()
	defer fake.deleteByIdHandlerMutex.RUnlock()
	argsForCall := fake.deleteByIdHandlerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHandlerInterface) GetEmployeeHandler(arg1 *gin.Context) {
	fake.getEmployeeHandlerMutex.Lock()
	fake.getEmployeeHandlerArgsForCall = append(fake.getEmployeeHandlerArgsForCall, struct {
		arg1 *gin.Context
	}{arg1})
	stub := fake.GetEmployeeHandlerStub
	fake.recordInvocation("GetEmployeeHandler", []interface{}{arg1})
	fake.getEmployeeHandlerMutex.Unlock()
	if stub != nil {
		fake.GetEmployeeHandlerStub(arg1)
	}
}

func (fake *FakeHandlerInterface) GetEmployeeHandlerCallCount() int {
	fake.getEmployeeHandlerMutex.RLock()
	defer fake.getEmployeeHandlerMutex.RUnlock()
	return len(fake.getEmployeeHandlerArgsForCall)
}

func (fake *FakeHandlerInterface) GetEmployeeHandlerCalls(stub func(*gin.Context)) {
	fake.getEmployeeHandlerMutex.Lock()
	defer fake.getEmployeeHandlerMutex.Unlock()
	fake.GetEmployeeHandlerStub = stub
}

func (fake *FakeHandlerInterface) GetEmployeeHandlerArgsForCall(i int) *gin.Context {
	fake.getEmployeeHandlerMutex.RLock()
	defer fake.getEmployeeHandlerMutex.RUnlock()
	argsForCall := fake.getEmployeeHandlerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHandlerInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createEmployeeHandlerMutex.RLock()
	defer fake.createEmployeeHandlerMutex.RUnlock()
	fake.deleteByIdHandlerMutex.RLock()
	defer fake.deleteByIdHandlerMutex.RUnlock()
	fake.getEmployeeHandlerMutex.RLock()
	defer fake.getEmployeeHandlerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHandlerInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ routes.HandlerInterface = new(FakeHandlerInterface)
