name: swagger-docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master", "dev" ]
    # Publish semver tags as releases.
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: on4treg.azurecr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: projectx
  DOCKER_USER: on4treg


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write





    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone SwagDeploy
        uses: actions/checkout@v2
        with:
          repository: wok-gocaspi/swagdeploy
          path: resources/swagdeploy
          ref: master